# One-time generator. Run on UNMODIFIED (baseline) code:
#   julia --project=. test/gen_periodic_velocity_baseline.jl
# It writes test/data/periodic_velocity_baseline.txt with pinned outputs, which
# test/test_periodic_velocity_regression.jl reads back. The format is one
# `[case]` line per kernel followed by one `ux uy` line per node (%.17g, so
# the Float64 values round-trip exactly).
using ContourDynamics
using StaticArrays
using Printf

const OUT = joinpath(@__DIR__, "data", "periodic_velocity_baseline.txt")

const CASES = (
    (name = "euler", kernel = EulerKernel()),
    (name = "qg",    kernel = QGKernel(1.0)),
    (name = "sqg",   kernel = SQGKernel(0.02)),
)

makeprob(kernel) = ContourProblem(kernel, PeriodicDomain(10.0, 10.0),
                                  [circular_patch(0.5, 200, 1.0)])

mkpath(dirname(OUT))
open(OUT, "w") do io
    println(io, "# AUTO-GENERATED by gen_periodic_velocity_baseline.jl on baseline code.")
    println(io, "# Pinned periodic single-layer velocity outputs read by")
    println(io, "# test_periodic_velocity_regression.jl. Regenerate only from a known-good")
    println(io, "# baseline (see the generator's header); do not edit by hand.")
    println(io, "# Format: a `[case]` line starts a block; each following line is `ux uy`")
    println(io, "# for one node, in node order.")
    for c in CASES
        prob = makeprob(c.kernel)
        vel = zeros(SVector{2,Float64}, total_nodes(prob))
        velocity!(vel, prob)
        println(io, "[", c.name, "]")
        for v in vel
            @printf(io, "%.17g %.17g\n", v[1], v[2])
        end
    end
end
println("wrote ", OUT)
