# One-time generator. Run on UNMODIFIED (baseline) code:
#   julia --project=. test/gen_periodic_velocity_baseline.jl
# It writes test/test_periodic_velocity_regression.jl with pinned outputs.
using ContourDynamics
using StaticArrays
using Printf

const OUT = joinpath(@__DIR__, "test_periodic_velocity_regression.jl")

const CASES = (
    (name = "euler", kexpr = "EulerKernel()",   kernel = EulerKernel()),
    (name = "qg",    kexpr = "QGKernel(1.0)",    kernel = QGKernel(1.0)),
    (name = "sqg",   kexpr = "SQGKernel(0.02)",  kernel = SQGKernel(0.02)),
)

makeprob(kernel) = ContourProblem(kernel, PeriodicDomain(10.0, 10.0),
                                  [circular_patch(0.5, 200, 1.0)])

open(OUT, "w") do io
    println(io, "# AUTO-GENERATED by gen_periodic_velocity_baseline.jl on baseline code.")
    println(io, "# Pins periodic single-layer velocity outputs to guard the dedup refactor.")
    println(io, "# Regenerate only from a known-good baseline; do not edit by hand.")
    println(io, "@testset \"Periodic velocity regression (refactor guard)\" begin")
    println(io, "    dom = PeriodicDomain(10.0, 10.0)")
    println(io, "    mkpatch() = circular_patch(0.5, 200, 1.0)")
    for c in CASES
        prob = makeprob(c.kernel)
        vel = zeros(SVector{2,Float64}, total_nodes(prob))
        velocity!(vel, prob)
        println(io)
        println(io, "    expected_$(c.name) = SVector{2,Float64}[")
        for v in vel
            @printf(io, "        SVector(%.17g, %.17g),\n", v[1], v[2])
        end
        println(io, "    ]")
        println(io, "    prob_$(c.name) = ContourProblem($(c.kexpr), dom, [mkpatch()])")
        println(io, "    vel_$(c.name) = zeros(SVector{2,Float64}, total_nodes(prob_$(c.name)))")
        println(io, "    velocity!(vel_$(c.name), prob_$(c.name))")
        println(io, "    @test all(isapprox.(vel_$(c.name), expected_$(c.name); rtol=1e-12, atol=1e-14))")
    end
    println(io, "end")
end
println("wrote ", OUT)
