name = "ContourDynamics"
uuid = "0a114e3f-4576-410c-8414-be1d36bbc63f"
version = "0.1.0"
authors = ["Subhajit Kar"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
GeophysicalFlows = "44ee3b1c-bc02-53fa-8355-8e347616e15e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecordedArrays = "ff8dd329-ec6c-4f0e-9d08-4b87e1122caa"

[extensions]
ContourDynamicsDiffEqExt = "OrdinaryDiffEq"
ContourDynamicsGeophysicalFlowsExt = "GeophysicalFlows"
ContourDynamicsJLD2Ext = "JLD2"
ContourDynamicsMakieExt = "Makie"
ContourDynamicsRecordedArraysExt = "RecordedArrays"

[compat]
GeophysicalFlows = "0.17, 0.16"
JLD2 = "0.5, 0.6"
Makie = "0.21, 0.22"
OrdinaryDiffEq = "6"
RecordedArrays = "0.4, 0.5"
SpecialFunctions = "2"
StaticArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
