name = "ContourDynamics"
uuid = "0a114e3f-4576-410c-8414-be1d36bbc63f"
authors = ["Subhajit Kar"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecordedArrays = "ff8dd329-ec6c-4f0e-9d08-4b87e1122caa"

[extensions]
ContourDynamicsCUDAExt = "CUDA"
ContourDynamicsDiffEqExt = "OrdinaryDiffEq"
ContourDynamicsJLD2Ext = "JLD2"
ContourDynamicsMakieExt = "Makie"
ContourDynamicsRecordedArraysExt = "RecordedArrays"

[compat]
Adapt = "4"
CUDA = "5"
JLD2 = "0.5, 0.6"
Makie = "0.21, 0.22"
KernelAbstractions = "0.9"
OrdinaryDiffEq = "6"
RecordedArrays = "0.4, 0.5"
SpecialFunctions = "2"
StaticArrays = "1"
julia = "1.10"

[extras]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JLD2"]
